# Generated by Django 2.2.11 on 2020-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInf',
            fields=[
                ('bookIssued', models.CharField(max_length=400, primary_key=True, serialize=False)),
            ],
        ),
    ]
